### ISSUE TITLE
Where did the R + Ruby example go?

### ISSUE THREAD

**Issue by stephenhmarsh** [virtualstaticvoid/heroku-docker-r#1]
In this project's README there is a link to a Ruby example in the examples repo:
https://github.com/virtualstaticvoid/heroku-docker-r-examples/tree/master/ruby

But I get a 404???

**Comment by virtualstaticvoid** [comment]
Sorry for the delay in sorting this out. The Ruby example is available now.

Checkout [heroku-docker-r-examples/ruby](https://github.com/virtualstaticvoid/heroku-docker-r-examples/tree/master/ruby).
