### ISSUE TITLE
Hi @virtualstaticvoid, we are still getting the error when trying to use the r-buildpack on one of our apps on Heroku. Do I need to do something in special to get the updated keys?

### ISSUE THREAD

**Issue by virtualstaticvoid** [virtualstaticvoid/heroku-docker-r#22]
Hi @virtualstaticvoid, we are still getting the error when trying to use the r-buildpack on one of our apps on Heroku. Do I need to do something in special to get the updated keys?

```
GPG error: https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease: The following signatures were invalid: EXPKEYSIG 51716619E084DAB9 Michael Rutter <marutter@gmail.com>
```

_Originally posted by @diegocl02 in https://github.com/virtualstaticvoid/heroku-docker-r/issues/20#issuecomment-716252379_

**Comment by diegocl02** [comment]
Thanks @virtualstaticvoid, I think you already fixed it here https://github.com/virtualstaticvoid/heroku-buildpack-r/issues/145
