### ISSUE TITLE
Deployment to Heroku fails when packages require R version > 4.2.2

### ISSUE THREAD

**Issue by olihawkins** [virtualstaticvoid/heroku-docker-r#28]
Thanks very much for these Docker images. We often use them for publishing R pipelines on Heroku.

Recently we ran into an issue where a pipeline ran locally on R version 4.4.0 but failed on deploying to Heroku with the `build` image because one of the packages in the project dependencies required a version of R later than 4.2.2.

Will these Docker images be maintained and updated going forward?

Thanks very much for your help.

**Comment by virtualstaticvoid** [comment]
Thanks for reporting the issue. I've created #29 for building the latest R version (4.4.2).
Once it gets merged, the new images will be published.

**Comment by olihawkins** [comment]
That's amazing. Thanks!
