### ISSUE TITLE
Is there a way to set stack to `container` via app.json?

### ISSUE THREAD

**Issue by firasm** [virtualstaticvoid/heroku-docker-r#5]
Hey there - thanks for all your work setting up this (and all the other repos) trying to get R apps deployed on heroku! I got my app deployed using your instructions.

I have a quick question, in your instructions the first step is:

> Run heroku create --stack=container from your R application source's root directory to create a container based application on Heroku.

Is there any way to complete this step without the heroku CLI? I'm trying to set up a tutorial for my students where I can create a new heroku app using the deploy button in a GitHub repo. You can of course set the build pack in app.json, and the heroku instructions even permit you to set `stack` to be `container` from `app.json`, but somehow this setting isn't respected **when first creating an app**. 

When I try to deploy my app (without creating the app and setting stack using CLI), I get the message:

```
 !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed
```

[here is the app.json file](https://github.com/firasm/dashR_deployed/blob/master/app.json)

**Comment by virtualstaticvoid** [comment]
Hi @firasm 

I [forked your repo](https://github.com/virtualstaticvoid/dashR_deployed) and made a change to the `app.json` file to include the [stack configuration](https://github.com/virtualstaticvoid/dashR_deployed/blob/master/app.json#L9) as per [Heroku docs](https://devcenter.heroku.com/articles/app-json-schema#stack).

Clicking the "deploy" button worked after that.
